image: node:10.18.0

stages:
  - build
  - deploy

cache:
  paths:
    - node_modules/

buildGatsby:
  stage: build
  script:
    - npm install
    - ./node_modules/.bin/gatsby build
  # specify the artifacts to save
  artifacts:
    paths:
      - public
  only:
    - release

deployGatsby:
  stage: deploy
  only:
  - release
  dependencies:
  - buildGatsby
  script:
  # Check for ssh-agent + rsync and install if not present
  - "which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y  )"
  - "which rsync || ( apt-get update -y && apt-get install rsync -y )"
  - eval $(ssh-agent -s)
  # Inject the remote's private key
  - echo -n "$SSH_PRIVATE_KEY" | tr -d '\r'
  - echo "========================="
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  # echo "$SSH_KNOWN_HOSTS"
  # Append keyscan output into known hosts
  - ssh-keyscan $SERVER_IP >> ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts
  # rsync -avuz --exclude=".*" $CI_PROJECT_DIR/dist/ $SERVER_USER@$SERVER_IP:/var/www/watchcrypto.today
  - rsync -avzh --delete public/* $SERVER_USER@$SERVER_IP:/var/www/ecomdiscover.com/html
  # Non interactive ssh gracefully reloads server
  - ssh $SERVER_USER@$SERVER_IP '. /etc/profile; pm2 reload all'
  # scp -i ~/.ssh/deploy_dev -r public/* deploy@159.203.38.209:/var/www/glennsheppard.dev/html
