image: node:10.18.0

stages:
  - build
  - deploy

cache:
  paths:
    - node_modules/

buildGatsby:
  stage: build
  script:
    - yarn install
    - ./node_modules/.bin/gatsby build --prefix-paths
  # specify the artifacts to save
  artifacts:
    paths:
      - public
  only:
    - release

deployGatsby:
  stage: deploy
  only:
  - release
  dependencies:
  - buildGatsby
  script:
  # Check for ssh-agent + rsync and install if not present
  - "which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y  )"
  - "which rsync || ( apt-get update -y && apt-get install rsync -y )"
  - eval $(ssh-agent -s)
  # Inject the remote's private key
  - echo "========================="
  - echo "$SSH_PRIVATE_KEY"
  - echo "========================="
  # - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
  - ssh-add <(echo "$SSH_PRIVATE_KEY" | base64 --decode)
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  # echo "$SSH_KNOWN_HOSTS"
  # Append keyscan output into known hosts
  - ssh-keyscan $SERVER_IP >> ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts
  # rsync -avuz --exclude=".*" $CI_PROJECT_DIR/dist/ $SERVER_USER@$SERVER_IP:/var/www/watchcrypto.today
  - rsync -avzh --delete public/* $SERVER_USER@$SERVER_IP:/var/www/ecomdiscover.com/html
  # rsync -avuz -e 'ssh -i ~/.ssh/deploy_rsa' $CI_PROJECT_DIR/dist/ $SERVER_USER@8.8.8.8:/var/wwww/example.com
  # Non interactive ssh gracefully reloads server
  # - ssh $SERVER_USER@$SERVER_IP '. /etc/profile; pm2 reload all'
