import React from "react"

import Layout from "../components/layout"
import SEO from "../components/seo"
//import Image from "../components/image"
import heroImg from "../images/apple-devices-books-business-coffee-572056.jpg"

function IndexPage() {
  return (
    <Layout>
      <SEO
        title="Home"
        keywords={[`amazon`, `seller`, `tools`, `FBA`]}
      />
      <div className="pt-24">

        <div className="container px-3 mx-auto flex flex-wrap flex-col md:flex-row items-center">

          <div className="flex flex-col w-full md:w-2/5 justify-center items-start text-center md:text-left">
            <p className="uppercase tracking-loose w-full">FIND TOP-RATED, CERTIFIED PROS FOR YOUR PROJECT</p>
            <h1 className="my-4 text-5xl font-bold leading-tight">GatsbyJS Tailwind Starter</h1>
            <p className="leading-normal text-2xl mb-8">
              a simple landing page styled with <a className="text-gray-800 font-bold underline" href="https://tailwindcss.com/">Tailwind CSS</a>
              {' '} and generated by <a className="text-gray-800 font-bold underline" href="https://www.gatsbyjs.org/">GatsbyJS</a>
            </p>

            <form action="submit">
              <button type="submit" className="mx-auto lg:mx-0 hover:underline bg-white text-gray-800 font-bold rounded-full my-6 py-4 px-8 shadow-lg">Get Sources</button>
            </form>

          </div>

          <div className="w-full md:w-3/5 py-6 text-center">
            <img className="w-full md:w-4/5 z-50" src={heroImg} />
          </div>

        </div>

      </div>
      <div>
        <h2></h2>
        <p>Find great businesses around the corner and across the country</p>
        <button>Find Tools</button>
      </div>
      <h1>Hi people</h1>
      <p>Welcome to E-Seller Tools.</p>
      <p>A collection of e-commerce resources. Primarily related to FBA, but also touching on many other aspects of e-commerce software and resources.</p>
    </Layout>
  )
}

export default IndexPage