name: Build & Deploy Site

on:
  # 1. Trigger the workflow
  push:
    branches:
      - master
  schedule:
    - cron: '0 4 * * *'
  repository_dispatch:
    types: [backend_automation]
      
jobs:
  build:
    # 2. Using the latest Ubuntu image
    runs-on: ubuntu-latest
    
    steps:
      # Check out the current repository code
      - uses: actions/checkout@v2
      # Install node
      - name: Set Node.js
        uses: actions/setup-node@master
        with:
          node-version: 10.x
      # Install all dependencies needed
      - name: Install Dependencies
        run: yarn install
      # Build the Gatsby site
      - name: Gatsby Build
        run: yarn run build
        env:
          GATSBY_FIREBASE_TYPE: ${{ secrets.GATSBY_FIREBASE_TYPE }}
          GATSBY_FIREBASE_PROJECT_ID: ${{ secrets.GATSBY_FIREBASE_PROJECT_ID }}
          GATSBY_FIREBASE_PRIVATE_KEY_ID: ${{ secrets.GATSBY_FIREBASE_PRIVATE_KEY_ID }}
          GATSBY_FIREBASE_PRIVATE_KEY: ${{ secrets.GATSBY_FIREBASE_PRIVATE_KEY }}
          GATSBY_FIREBASE_CLIENT_EMAIL: ${{ secrets.GATSBY_FIREBASE_CLIENT_EMAIL }}
          GATSBY_FIREBASE_CLIENT_ID: ${{ secrets.GATSBY_FIREBASE_CLIENT_ID }}
          GATSBY_FIREBASE_AUTH_URI: ${{ secrets.GATSBY_FIREBASE_AUTH_URI }}
          GATSBY_FIREBASE_TOKEN_URI: ${{ secrets.GATSBY_FIREBASE_TOKEN_URI }}
          GATSBY_FIREBASE_AUTH_PROVIDER_X509_CERT_URL: ${{ secrets.GATSBY_FIREBASE_AUTH_PROVIDER_X509_CERT_URL }}
          GATSBY_FIREBASE_CLIENT_X509_CERT_URL: ${{ secrets.GATSBY_FIREBASE_CLIENT_X509_CERT_URL }}
          GATSBY_FIREBASE_API_KEY: ${{ secrets.GATSBY_FIREBASE_API_KEY }}
          GATSBY_FIREBASE_AUTH_DOMAIN: ${{ secrets.GATSBY_FIREBASE_AUTH_DOMAIN }}
          GATSBY_FIREBASE_DATABASE_URL: ${{ secrets.GATSBY_FIREBASE_DATABASE_URL }}
          GATSBY_FIREBASE_STORAGE_BUCKET: ${{ secrets.GATSBY_FIREBASE_STORAGE_BUCKET }}
          GATSBY_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.GATSBY_FIREBASE_MESSAGING_SENDER_ID }}
          GATSBY_FIREBASE_APP_ID: ${{ secrets.GATSBY_FIREBASE_APP_ID }}
          GATSBY_FIREBASE_MEASUREMENT_ID: ${{ secrets.GATSBY_FIREBASE_MEASUREMENT_ID }}
      # Sync the built files to the remote server
      - name: Rsync deployment
        uses: burnett01/rsync-deployments@4.1
        with:
          switches: -avzh --delete
          path: public/
          remote_path: ${{ secrets.SERVER_PATH }}
          remote_host: ${{ secrets.SERVER_IP }}
          remote_user: ${{ secrets.SERVER_USER }}
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
